// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvtvvcwqabdtnyhtbpxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dHZ2Y3dxYWJkdG55aHRicHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDQzNjIsImV4cCI6MjA2MTUyMDM2Mn0.TLDr6iUHcY8RYh-8Ikh31ic11MaLA2H0f5XffzX9KNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);